// Code generated by @vegaprotocol/jsonrpc-generator@<%= version %>. DO NOT EDIT.
import { Transaction as VegaTransaction, TransactionModel } from '@vegaprotocol/transactions'
export { TransactionModel }

export { WalletClient } from './client'
export { WalletModel, Identifier, WalletClientHandler, ResponseError } from './model'