module.exports = {
  screens: {
    xs: '500px',
    sm: '640px',
    md: '768px',
    lg: '960px',
    xl: '1280px',
    xxl: '1536px',
  },
  colors: {
    transparent: 'transparent',
    current: 'currentColor',
    black: '#101010',
    white: '#fff',
    danger: {
      DEFAULT: '#FF261A',
    },
    warning: {
      DEFAULT: '#FF7A1A',
    },
    success: {
      DEFAULT: '#00F780',
    },
    yellow: {
      DEFAULT: '#D7FB50',
      dark: '#9BE106',
    },
    pink: {
      DEFAULT: '#FF077F',
      dark: '#CF0064',
    },
    green: {
      DEFAULT: '#00F780',
      dark: '#00D46E',
    },
    blue: {
      DEFAULT: '#0075FF',
      dark: '#0046CD',
    },
    purple: {
      DEFAULT: '#8028FF',
      dark: '#5D0CD2',
    },
    dark: {
      100: '#161616',
      200: '#404040',
      300: '#8B8B8B',
      400: '#C0C0C0',
    },
    light: {
      100: '#F0F0F0',
      200: '#D2D2D2',
      300: '#A7A7A7',
      400: '#626262',
    },
    neutral: {
      DEFAULT: '#6E6E6E',
    },
    emphasise: '#F5F8fA',
    deemphasise: '#8A9BA8',
    primary: {
      DEFAULT: '#48aff8',
    },
    overlay: 'rgba(54, 54, 54, 0.8)',
  },
  spacing: {
    1: '2px',
    2: '6px',
    3: '10px',
  },
  fontSize: {
    xs: '12px',
    sm: '14px',
    base: '16px',
    xl: '20xp',
    '2xl': '24px',
    '3xl': '28px',
    '4xl': '32px',
  },
  letterSpacing: {
    tightest: '-.075em',
    tighter: '-.05em',
    tight: '-.025em',
    normal: '0',
    wide: '.025em',
    wider: '.05em',
    widest: '.3em',
  },
  fontFamily: {
    mono: ['Roboto Mono', 'monospace'],
    sans: [
      '"Helvetica Neue"',
      '-apple-system',
      'BlinkMacSystemFont',
      '"Segoe UI"',
      'Roboto',
      'Arial',
      '"Noto Sans"',
      'sans-serif',
      '"Apple Color Emoji"',
      '"Segoe UI Emoji"',
      '"Segoe UI Symbol"',
      '"Noto Color Emoji"',
    ],
    alpha: [
      'AlphaLyrae',
      '"Helvetica Neue"',
      '-apple-system',
      'BlinkMacSystemFont',
      '"Segoe UI"',
      'Roboto',
      'Arial',
      '"Noto Sans"',
      'sans-serif',
      '"Apple Color Emoji"',
      '"Segoe UI Emoji"',
      '"Segoe UI Symbol"',
      '"Noto Color Emoji"',
    ],
  },
}
