name: UI mocked tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
  workflow_dispatch:
jobs:
  name: Test and lint - PR
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.0
        cache: yarn

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run tests
      run: yarn e2e:run --browser chrome --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
