name: UI mocked tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
  workflow_dispatch:
jobs:
  ui-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Serve wallet-mock
        run: yarn test wallet-ui:serve &

      - name: Install playwright dependencies
        run: |
          yarn playwright install
          yarn playwright install-deps chromium

      - name: Run tests
        run: yarn e2e --verbose --skip-nx-cache

      - name: Show test summary
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: UI Tests
          path: apps/wallet-mock/test-results/junit-report/report.xml
          reporter: java-junit

      - name: Upload test report artifact in case of failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: apps/wallet-mock/test-results
