name: UI mocked tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
  workflow_dispatch:
jobs:
  ui-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install playwright dependencies
        run: yarn playwright install --with-deps

      - name: Run tests
        run: yarn e2e:percy --record
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
